<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-01T20:13:11 IST" name="Default suite" finished-at="2024-04-01T20:13:11 IST" duration-ms="60">
    <groups>
    </groups>
    <test started-at="2024-04-01T20:13:11 IST" name="Default test" finished-at="2024-04-01T20:13:11 IST" duration-ms="60">
      <class name="OddEvenPrime.OddEvenPrime.OEPTest">
        <test-method signature="testEven()[pri:0, instance:OddEvenPrime.OddEvenPrime.OEPTest@14cd1699]" started-at="2024-04-01T20:13:11 IST" name="testEven" finished-at="2024-04-01T20:13:11 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEven -->
        <test-method signature="testOdd()[pri:0, instance:OddEvenPrime.OddEvenPrime.OEPTest@14cd1699]" started-at="2024-04-01T20:13:11 IST" name="testOdd" finished-at="2024-04-01T20:13:11 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<ODD> but was:<PRIME>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<ODD> but was:<PRIME>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at OddEvenPrime.OddEvenPrime.OEPTest.testOdd(OEPTest.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOdd -->
        <test-method signature="testPrime()[pri:0, instance:OddEvenPrime.OddEvenPrime.OEPTest@14cd1699]" started-at="2024-04-01T20:13:11 IST" name="testPrime" finished-at="2024-04-01T20:13:11 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrime -->
      </class> <!-- OddEvenPrime.OddEvenPrime.OEPTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
